CREATE TABLE IF NOT EXISTS USERS (
	UserID INT PRIMARY KEY,
	Name VARCHAR(512) DEFAULT NULL,
	Email VARCHAR(512) DEFAULT NULL,
	Spaces INT DEFAULT 1,
	Targets INT[] DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS SPACES (
	SpaceID INT PRIMARY KEY NOT NULL,	
	Location VARCHAR(32) DEFAULT 'Subsolo',
	IsBlocked BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS DRAW (
	DrawID SERIAL PRIMARY KEY,
	CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,	
	Description TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS DRAW_RESULT (	
	CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,	
	DrawID INT REFERENCES DRAW(DrawID),
	SpaceID INT REFERENCES SPACES(SpaceID),
	UserID INT REFERENCES USERS(UserID)
);

CREATE TABLE IF NOT EXISTS LOG (
	LogID SERIAL PRIMARY KEY,
	CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,	
	Message TEXT NOT NULL
);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO bianca;